services:
  app-db:
    image: postgres:16
    container_name: bloodhound-postgres
    restart: unless-stopped
    environment:
      - PGUSER=bloodhound
      - POSTGRES_USER=bloodhound
      - POSTGRES_PASSWORD=bloodhoundcommunityedition
      - POSTGRES_DB=bloodhound
    ports:
      - "127.0.0.1:5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bloodhound -d bloodhound -h 127.0.0.1 -p 5432"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  graph-db:
    image: neo4j:4.4.42
    container_name: bloodhound-neo4j
    restart: unless-stopped
    environment:
      - NEO4J_AUTH=neo4j/bloodhoundcommunityedition
      - NEO4J_dbms_allow__upgrade=true
    ports:
      - "127.0.0.1:7687:7687"
      - "127.0.0.1:7474:7474"
    volumes:
      - neo4j_data:/data
    healthcheck:
      test: ["CMD-SHELL", "wget -O /dev/null -q http://localhost:7474 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  bloodhound:
    image: specterops/bloodhound:latest
    container_name: bloodhound
    restart: unless-stopped
    environment:
      - bhe_disable_cypher_complexity_limit=false
      - bhe_enable_cypher_mutations=true
      - bhe_graph_query_memory_limit=2
      - bhe_database_connection=user=bloodhound password=bloodhoundcommunityedition dbname=bloodhound host=app-db
      - bhe_neo4j_connection=neo4j://neo4j:bloodhoundcommunityedition@graph-db:7687/
      - bhe_recreate_default_admin=false
      - bhe_graph_driver=neo4j
    ports:
      - "127.0.0.1:8880:8080"
    depends_on:
      app-db:
        condition: service_healthy
      graph-db:
        condition: service_healthy

volumes:
  neo4j_data:
  postgres_data:
